#
# settings related to recompiling and reruning app when source changes
#

[app]
    mode = "release"
    data_path = "/stocks/data"   # 数据的存放路径
    [app.logger]
        level = "DEBUG"
        name = "ctdx"

# 通达信一些配置参数
[tdx]
    [tdx.urls]
        stock_fin = "http://down.tdx.com.cn:8001/fin"
        fin_list_file = "gpcw.txt"  # 财务数据文件列表
    [tdx.files]
        calendar = "/base/calendar.csv.zip"                  # 股票交易日历
        stock_list = "/base/stocks.csv.zip"                  # 通达信商品(股票、基金、指数、债券等)列表信息
        stock_bonus = "/base/bonus.csv.zip"                  # 存放每只股票的分红配股信息
        stock_day = "/history/days/"                         # 每只股票的日K数据
        stock_min = "/history/mins/"                         # 每只股票的5分钟数据
        stock_report = "/report/%s"                          # 存放每只股票的财务报告
    [tdx.server]
        data_host = "121.14.110.200:443"
        monitor_host= "121.14.110.200:443"
